### ISSUE TITLE
Enhance onboarding page with screen shots

### ISSUE THREAD

**Issue by rogilmore** [databrary/guide#23]
https://databrary.github.io/guide/onboarding.html

**Comment by YingheLiu5579** [comment]
In the onboarding section, there are three major components based on the personnel profile: for Authorized Investigators, for Affiliations, and a Tour of the Databrary Dashboard. I may only contribute to the affiliations part and tour of the dashboard, since I do not join the databrary as an authorized investigator.

**Comment by YingheLiu5579** [comment]
Add ## Button Dictionary that illustrates how to highlight volumes or check accessibility.
